### ISSUE TITLE
msgEdit and msgDelete not working

### ISSUE THREAD

**Issue by rootandy** [viegener/Telegram-fhem#11]
Editing and deleting messages (or anything else like queries) is not working since the msgId is not sent. So in Groups messages can't be edited.

**Comment by viegener** [comment]
Hi rootandy,
not sure what issue you are refering to - just tested again - msgEdit and msgDelete are working in groups and single contact chats.

Not sure what you are refering to with "since the msgId is not sent"

**Comment by viegener** [comment]
Closed due to no response received
