### ISSUE TITLE
New Login Method -  fhem integration will stop working May 11th if login method is not changed 

### ISSUE THREAD

**Issue by buhao75** [viegener/Telegram-fhem#14]
Yesterday I received the following email from blink:

Notice: Disabling Unauthorized 3rd Party Automation Scripts

Dear Blink Customer,
--
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | 

The topic is also discussed in other projects: https://github.com/fronzbot/blinkpy/issues/210

I hope that there is a possibility to keep fhem <-> blink integration working in the future. 

Thanks in advance!

**Comment by viegener** [comment]
Yes, also following the corresponding different threads (not just in github) and contacted blink directly - so far have not seen a solution - if there is a new login possibility I would also like to enable this

**Comment by buhao75** [comment]
I have installed the new version of the script and it is working again. Thanks for fixing!
