### ISSUE TITLE
verweiste Codes in defptr

### ISSUE THREAD

**Issue by habeIchVergessen** [viegener/Telegram-fhem#5]
vielleicht kann der Test mehr sagen als Worte (Skripte für FHEM):
- alle Codes auflisten
  `{ foreach my $c ( keys %{ $modules{SOMFY}{defptr} } ) { Log3(1, "Test", "c: $c");; foreach my $dname ( keys %{ $modules{SOMFY}{defptr}{$c} } ) { Log3(1, "Test", "-> dname: $dname, #" . int(( keys %{ $modules{SOMFY}{defptr}{$c} } )) . ", defined: " . (defined($defs{$dname}) ? "yes" : "no"));; } } }`
- neues Device anlegen
  `define SomfyTest SOMFY AFBECD`
- alle Codes auflisten
  `{ foreach my $c ( keys %{ $modules{SOMFY}{defptr} } ) { Log3(1, "Test", "c: $c");; foreach my $dname ( keys %{ $modules{SOMFY}{defptr}{$c} } ) { Log3(1, "Test", "-> dname: $dname, #" . int(( keys %{ $modules{SOMFY}{defptr}{$c} } )) . ", defined: " . (defined($defs{$dname}) ? "yes" : "no"));; } } }`
- Device löschen
  `delete SomfyTest`
- alle Codes auflisten
  `{ foreach my $c ( keys %{ $modules{SOMFY}{defptr} } ) { Log3(1, "Test", "c: $c");; foreach my $dname ( keys %{ $modules{SOMFY}{defptr}{$c} } ) { Log3(1, "Test", "-> dname: $dname, #" . int(( keys %{ $modules{SOMFY}{defptr}{$c} } )) . ", defined: " . (defined($defs{$dname}) ? "yes" : "no"));; } } }`

In der Liste sollte folgender Eintrag vorkommen.
`Test: c: AFBECD`
Jedoch gibt es keine nachfolgende Zeile.
`-> dname: SomfyTest, #1, defined: yes`

Solange der Code in der Liste steht, funktioniert Autocreate nicht mehr.
- aufräumen (nicht referenzierte Codes löschen)
  `{ foreach my $c ( keys %{ $modules{SOMFY}{defptr} } ) { Log3(1, "Test", "c: $c");; foreach my $dname ( keys %{ $modules{SOMFY}{defptr}{$c} } ) { delete $modules{SOMFY}{defptr}{$c}{$dname} if (!defined($defs{$dname}));; };; delete $modules{SOMFY}{defptr}{$c} if (int((keys %{ $modules{SOMFY}{defptr}{$c} } )) == 0);; } }`

**Comment by viegener** [comment]
Gelöst: _Parse prüft jetzt auch auf leeren Hash zu einer Adresse und gibt dann UNDEFINED zurück (für autocreate)

Das heisst aber nicht dass autocreate funktioniert, das ist bisher keine unterstützte Funktionalität
