### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by bukibody** [viegener/Telegram-fhem#7]
Das reading PollingLastError  zeigt seit gestern folgendes:

Callback returned no valid JSON: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<html>\r\n<head><tit...") at ./FHEM/50_TelegramBot.pm line 1631.

**Comment by viegener** [comment]
Based on the description, this is not considered a bug, but normale behavior in case the telegrambot is receiving an invalid response from the telegram server. In this case it seems to be an error / outage message from telegram (i.e. probably an html file) and not the JSON response with data on received messages
